const { pool } = require("../services/databaseService");

const {
    getSchemeRecommendations
} = require("../services/aiService");


/*
    Official application portals that have been
    verified separately from the AI response.

    IMPORTANT:
    Do not add a URL here unless it has been
    verified as an official government portal.
*/
const VERIFIED_SCHEME_URLS = {

    "pm kisan":
        "https://www.pmkisan.gov.in/RegistrationFormupdated.aspx",

    "pradhan mantri kisan samman nidhi":
        "https://www.pmkisan.gov.in/RegistrationFormupdated.aspx",

    "pmfby":
        "https://pmfby.gov.in/farmerRegistrationForm",

    "pradhan mantri fasal bima yojana":
        "https://pmfby.gov.in/farmerRegistrationForm",

    "soil health card":
        "https://soilhealth.dac.gov.in/",

    "soil health card scheme":
        "https://soilhealth.dac.gov.in/",

    "pradhan mantri krishi sinchayee yojana":
        "https://pmksy.gov.in/",

    "pmksy":
        "https://pmksy.gov.in/"
};


/*
    Official fallback portal.

    When we do not know a verified direct
    application URL for a scheme, we send
    the farmer to the official myScheme portal.

    IMPORTANT:
    This URL is NOT generated by AI.
*/
const MYSCHEME_URL =
    "https://www.myscheme.gov.in/";


/*
    Normalize scheme names so that small differences
    in AI-generated names do not prevent matching.
*/
function normalizeSchemeName(name) {

    return name
        .toLowerCase()
        .replace(/[()]/g, " ")
        .replace(/[^a-z0-9\s]/g, "")
        .replace(/\s+/g, " ")
        .trim();
}


/*
    Find the official application URL.

    Priority:

    1. Verified direct government URL
    2. Official myScheme fallback

    We completely ignore any URL generated by AI.
*/
function getApplicationDetails(schemeName) {

    const normalizedName =
        normalizeSchemeName(schemeName);


    /*
        Exact known scheme matches.
    */
    if (VERIFIED_SCHEME_URLS[normalizedName]) {

        return {
            application_url:
                VERIFIED_SCHEME_URLS[normalizedName],

            application_type:
                "direct_official"
        };
    }


    /*
        PM-KISAN variations.
    */
    if (
        normalizedName.includes("pm kisan") ||
        normalizedName.includes(
            "pradhan mantri kisan samman nidhi"
        )
    ) {

        return {
            application_url:
                VERIFIED_SCHEME_URLS["pm kisan"],

            application_type:
                "direct_official"
        };
    }


    /*
        PMFBY variations.
    */
    if (
        normalizedName.includes("pmfby") ||
        normalizedName.includes(
            "pradhan mantri fasal bima yojana"
        ) ||
        normalizedName.includes("fasal bima")
    ) {

        return {
            application_url:
                VERIFIED_SCHEME_URLS["pmfby"],

            application_type:
                "direct_official"
        };
    }


    /*
        Soil Health Card variations.
    */
    if (
        normalizedName.includes("soil health card")
    ) {

        return {
            application_url:
                VERIFIED_SCHEME_URLS["soil health card"],

            application_type:
                "direct_official"
        };
    }


    /*
        PMKSY variations.
    */
    if (
        normalizedName.includes("pmksy") ||
        normalizedName.includes(
            "pradhan mantri krishi sinchayee yojana"
        )
    ) {

        return {
            application_url:
                VERIFIED_SCHEME_URLS["pmksy"],

            application_type:
                "direct_official"
        };
    }


    /*
        Unknown scheme.

        DO NOT guess a scheme-specific URL.

        Use the official Government of India
        myScheme platform instead.
    */
    return {

        application_url:
            MYSCHEME_URL,

        application_type:
            "myscheme_fallback"
    };
}


/*
    Remove duplicate schemes returned by AI.
*/
function removeDuplicateSchemes(schemes) {

    const seen = new Set();

    return schemes.filter((scheme) => {

        const normalizedName =
            normalizeSchemeName(scheme.scheme_name);

        let identity = normalizedName;


        /*
            PM-KISAN identity.
        */
        if (
            normalizedName.includes("pm kisan") ||
            normalizedName.includes(
                "pradhan mantri kisan samman nidhi"
            )
        ) {

            identity = "pm kisan";
        }


        /*
            PMFBY identity.
        */
        if (
            normalizedName.includes("pmfby") ||
            normalizedName.includes("fasal bima")
        ) {

            identity = "pmfby";
        }


        /*
            Soil Health Card identity.
        */
        if (
            normalizedName.includes("soil health card")
        ) {

            identity = "soil health card";
        }


        /*
            PMKSY identity.
        */
        if (
            normalizedName.includes("pmksy") ||
            normalizedName.includes(
                "pradhan mantri krishi sinchayee yojana"
            )
        ) {

            identity = "pmksy";
        }


        if (seen.has(identity)) {
            return false;
        }


        seen.add(identity);

        return true;
    });
}


/*
    Clean and validate the schemes returned by AI.
*/
function validateSchemes(aiResponse) {

    if (
        !aiResponse ||
        typeof aiResponse !== "object"
    ) {

        return [];
    }


    if (!Array.isArray(aiResponse.schemes)) {
        return [];
    }


    const cleanedSchemes =
        aiResponse.schemes
            .filter((scheme) => {

                return (
                    scheme &&
                    typeof scheme === "object" &&
                    typeof scheme.scheme_name === "string" &&
                    scheme.scheme_name.trim() !== ""
                );

            })
            .map((scheme) => {

                /*
                    IMPORTANT:

                    We completely ignore the
                    application_url returned by AI.

                    The backend decides the URL.
                */
                const applicationDetails =
                    getApplicationDetails(
                        scheme.scheme_name
                    );


                return {

                    scheme_name:
                        scheme.scheme_name.trim(),

                    description:
                        typeof scheme.description === "string"
                            ? scheme.description.trim()
                            : "",

                    benefits:
                        Array.isArray(scheme.benefits)
                            ? scheme.benefits
                                .filter(
                                    item =>
                                        typeof item === "string"
                                )
                                .map(
                                    item => item.trim()
                                )
                                .filter(Boolean)
                            : [],

                    eligibility:
                        Array.isArray(scheme.eligibility)
                            ? scheme.eligibility
                                .filter(
                                    item =>
                                        typeof item === "string"
                                )
                                .map(
                                    item => item.trim()
                                )
                                .filter(Boolean)
                            : [],

                    state:
                        typeof scheme.state === "string"
                            ? scheme.state.trim()
                            : "",

                    application_url:
                        applicationDetails.application_url,

                    application_type:
                        applicationDetails.application_type

                };

            });


    /*
        Remove duplicate schemes after cleaning.
    */
    return removeDuplicateSchemes(
        cleanedSchemes
    );
}


/*
    GET /api/schemes/me

    Gets government schemes for the
    currently authenticated farmer.
*/
async function getMySchemes(req, res) {

    try {

        /*
            userId comes from the verified JWT.
        */
        const userId =
            req.user.userId;


        /*
            Get the farmer profile belonging
            to the logged-in user.
        */
        const [rows] =
            await pool.execute(
                `SELECT *
                 FROM farmer_profiles
                 WHERE user_id = ?`,
                [userId]
            );


        /*
            Check whether the user has
            created a farmer profile.
        */
        if (rows.length === 0) {

            return res.status(404).json({

                success: false,

                message:
                    "Farmer profile not found. Please create your farmer profile first."

            });

        }


        const farmer = rows[0];


        console.log(
            `Generating government schemes for user ${userId}, farmer profile ${farmer.id}...`
        );


        /*
            Send farmer information to AI service.
        */
        const aiResult =
            await getSchemeRecommendations(
                farmer
            );


        /*
            AI may sometimes return Markdown
            code fences.
        */
        let cleanedResponse =
            aiResult.trim();


        if (
            cleanedResponse.startsWith("```")
        ) {

            cleanedResponse =
                cleanedResponse
                    .replace(
                        /^```json\s*/i,
                        ""
                    )
                    .replace(
                        /^```\s*/i,
                        ""
                    )
                    .replace(
                        /\s*```$/i,
                        ""
                    )
                    .trim();

        }


        /*
            Convert AI response into JavaScript object.
        */
        let parsedResponse;


        try {

            parsedResponse =
                JSON.parse(
                    cleanedResponse
                );

        } catch (error) {

            console.error(
                "AI JSON Parse Error:",
                error.message
            );

            console.error(
                "AI Raw Response:",
                aiResult
            );


            return res.status(502).json({

                success: false,

                message:
                    "AI returned an invalid scheme response"

            });

        }


        /*
            Validate, deduplicate and attach
            verified official URLs.
        */
        const schemes =
            validateSchemes(
                parsedResponse
            );


        /*
            Return clean response to frontend.
        */
        return res.json({

            success: true,

            profile: {

                id: farmer.id,

                state: farmer.state,

                district: farmer.district,

                land_size: farmer.land_size,

                land_unit: farmer.land_unit,

                crop_type: farmer.crop_type,

                farming_type:
                    farmer.farming_type

            },

            schemes

        });


    } catch (error) {

        console.error(
            "Government Schemes Controller Error:",
            error
        );


        return res.status(500).json({

            success: false,

            message:
                "Failed to fetch government schemes"

        });

    }
}


module.exports = {
    getMySchemes
};