const { pool } = require("../services/databaseService");

const {
    getSchemeRecommendations
} = require("../services/aiService");


/*
    Official application portals that have been
    verified separately from the AI response.

    IMPORTANT:
    Do not add a URL here unless it has been
    verified as an official government portal.
*/
const VERIFIED_SCHEME_URLS = {

    "pm kisan": "https://www.pmkisan.gov.in/RegistrationFormupdated.aspx",

    "pradhan mantri kisan samman nidhi":
        "https://www.pmkisan.gov.in/RegistrationFormupdated.aspx",

    "pmfby":
        "https://pmfby.gov.in/farmerRegistrationForm",

    "pradhan mantri fasal bima yojana":
        "https://pmfby.gov.in/farmerRegistrationForm",

    "soil health card":
        "https://soilhealth.dac.gov.in/",

    "soil health card scheme":
        "https://soilhealth.dac.gov.in/",

    "pradhan mantri krishi sinchayee yojana":
        "https://pmksy.gov.in/",

    "pmksy":
        "https://pmksy.gov.in/"
};


/*
    Normalize scheme names so that small differences
    in AI-generated names do not prevent matching.
*/
function normalizeSchemeName(name) {

    return name
        .toLowerCase()
        .replace(/[()]/g, " ")
        .replace(/[^a-z0-9\s]/g, "")
        .replace(/\s+/g, " ")
        .trim();
}


/*
    Find a verified official URL based on the
    scheme name.

    We deliberately ignore the URL generated by AI.
*/
function getVerifiedApplicationUrl(schemeName) {

    const normalizedName =
        normalizeSchemeName(schemeName);


    /*
        Exact known scheme matches
    */
    if (VERIFIED_SCHEME_URLS[normalizedName]) {
        return VERIFIED_SCHEME_URLS[normalizedName];
    }


    /*
        PM-KISAN variations
    */
    if (
        normalizedName.includes("pm kisan") ||
        normalizedName.includes(
            "pradhan mantri kisan samman nidhi"
        )
    ) {
        return VERIFIED_SCHEME_URLS["pm kisan"];
    }


    /*
        PMFBY variations
    */
    if (
        normalizedName.includes("pmfby") ||
        normalizedName.includes(
            "pradhan mantri fasal bima yojana"
        ) ||
        normalizedName.includes("fasal bima")
    ) {
        return VERIFIED_SCHEME_URLS["pmfby"];
    }


    /*
        Soil Health Card variations
    */
    if (
        normalizedName.includes("soil health card")
    ) {
        return VERIFIED_SCHEME_URLS["soil health card"];
    }


    /*
        PMKSY variations
    */
    if (
        normalizedName.includes("pmksy") ||
        normalizedName.includes(
            "pradhan mantri krishi sinchayee yojana"
        )
    ) {
        return VERIFIED_SCHEME_URLS["pmksy"];
    }


    /*
        Unknown scheme:
        Do NOT guess the URL.
    */
    return null;
}


/*
    Remove duplicate schemes returned by AI.

    Example:
    PM-KISAN
    PM Kisan Samman Nidhi
    Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)

    These should not appear as three separate cards.
*/
function removeDuplicateSchemes(schemes) {

    const seen = new Set();

    return schemes.filter((scheme) => {

        const normalizedName =
            normalizeSchemeName(scheme.scheme_name);


        /*
            Create a simplified identity for
            common schemes.
        */
        let identity = normalizedName;


        if (
            normalizedName.includes("pm kisan") ||
            normalizedName.includes(
                "pradhan mantri kisan samman nidhi"
            )
        ) {
            identity = "pm kisan";
        }


        if (
            normalizedName.includes("pmfby") ||
            normalizedName.includes("fasal bima")
        ) {
            identity = "pmfby";
        }


        if (
            normalizedName.includes("soil health card")
        ) {
            identity = "soil health card";
        }


        if (
            normalizedName.includes("pmksy") ||
            normalizedName.includes(
                "pradhan mantri krishi sinchayee yojana"
            )
        ) {
            identity = "pmksy";
        }


        if (seen.has(identity)) {
            return false;
        }


        seen.add(identity);

        return true;
    });
}


/*
    Clean and validate the schemes returned by AI.
*/
function validateSchemes(aiResponse) {

    if (!aiResponse || typeof aiResponse !== "object") {
        return [];
    }


    if (!Array.isArray(aiResponse.schemes)) {
        return [];
    }


    const cleanedSchemes =
        aiResponse.schemes
            .filter((scheme) => {

                return (
                    scheme &&
                    typeof scheme === "object" &&
                    typeof scheme.scheme_name === "string" &&
                    scheme.scheme_name.trim() !== ""
                );

            })
            .map((scheme) => {

                /*
                    IMPORTANT:
                    We completely ignore the AI-generated
                    application_url.

                    The backend decides the URL.
                */
                const verifiedApplicationUrl =
                    getVerifiedApplicationUrl(
                        scheme.scheme_name
                    );


                return {

                    scheme_name:
                        scheme.scheme_name.trim(),

                    description:
                        typeof scheme.description === "string"
                            ? scheme.description.trim()
                            : "",

                    benefits:
                        Array.isArray(scheme.benefits)
                            ? scheme.benefits
                                .filter(
                                    item =>
                                        typeof item === "string"
                                )
                                .map(
                                    item => item.trim()
                                )
                                .filter(Boolean)
                            : [],

                    eligibility:
                        Array.isArray(scheme.eligibility)
                            ? scheme.eligibility
                                .filter(
                                    item =>
                                        typeof item === "string"
                                )
                                .map(
                                    item => item.trim()
                                )
                                .filter(Boolean)
                            : [],

                    state:
                        typeof scheme.state === "string"
                            ? scheme.state.trim()
                            : "",

                    application_url:
                        verifiedApplicationUrl

                };

            });


    /*
        Remove duplicate schemes after cleaning.
    */
    return removeDuplicateSchemes(cleanedSchemes);
}


/*
    GET /api/schemes/:profileId

    Example:
    GET http://localhost:5000/api/schemes/1
*/
async function getSchemes(req, res) {

    try {

        const { profileId } = req.params;

        const id = Number(profileId);


        /*
            Validate profile ID
        */
        if (
            !Number.isInteger(id) ||
            id <= 0
        ) {

            return res.status(400).json({

                success: false,

                message:
                    "Profile ID must be a valid positive integer"

            });

        }


        /*
            Get farmer profile from MySQL
        */
        const [rows] =
            await pool.execute(
                "SELECT * FROM farmer_profiles WHERE id = ?",
                [id]
            );


        /*
            Check whether farmer profile exists
        */
        if (rows.length === 0) {

            return res.status(404).json({

                success: false,

                message:
                    "Farmer profile not found"

            });

        }


        const farmer = rows[0];


        console.log(
            `Generating government schemes for farmer profile ${id}...`
        );


        /*
            Send farmer information to AI service
        */
        const aiResult =
            await getSchemeRecommendations(farmer);


        /*
            AI may sometimes return Markdown
            code fences.
        */
        let cleanedResponse =
            aiResult.trim();


        if (
            cleanedResponse.startsWith("```")
        ) {

            cleanedResponse =
                cleanedResponse
                    .replace(
                        /^```json\s*/i,
                        ""
                    )
                    .replace(
                        /^```\s*/i,
                        ""
                    )
                    .replace(
                        /\s*```$/i,
                        ""
                    )
                    .trim();

        }


        /*
            Convert AI response into JavaScript object.
        */
        let parsedResponse;


        try {

            parsedResponse =
                JSON.parse(cleanedResponse);

        } catch (error) {

            console.error(
                "AI JSON Parse Error:",
                error.message
            );

            console.error(
                "AI Raw Response:",
                aiResult
            );

            return res.status(502).json({

                success: false,

                message:
                    "AI returned an invalid scheme response"

            });

        }


        /*
            Validate, deduplicate and attach
            verified official URLs.
        */
        const schemes =
            validateSchemes(parsedResponse);


        /*
            Return clean response to frontend.
        */
        return res.json({

            success: true,

            profile: {

                id: farmer.id,

                state: farmer.state,

                district: farmer.district,

                land_size: farmer.land_size,

                land_unit: farmer.land_unit,

                crop_type: farmer.crop_type,

                farming_type:
                    farmer.farming_type

            },

            schemes

        });


    } catch (error) {

        console.error(
            "Government Schemes Controller Error:",
            error
        );


        return res.status(500).json({

            success: false,

            message:
                "Failed to fetch government schemes"

        });

    }
}


module.exports = {
    getSchemes
};